name: Reusable Deploy
on: workflow_call
jobs:
    deploy_TEST:
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              run: echo "Deploying and uploading...TEST"